### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by attilaz** [KTXSoftware/krafix#19]
Hi,

I have just found this repository. It looks like something that I could use.  Currently we only support essl shaders, but I would like to add support to our engine (which is based on bgfx) for metal shaders, vulkan spir-v and d3d9. From what I see this lib could be used for this. 

My plans are to compile shader source to spir-v(possible using khronos' compiler), than do some modification (constant specialication then dead code removal), then convert this shaders to metalsl, d3d9 and opengl shaders.
Is these possible with your lib?

Anyway, I think It would be great to have some info (readme file) about the goal of this project, how-to-use description, current state of the project.

Thanks

**Comment by RobDangerous** [comment]
krafix compiles to SPIR-V using Khronos' GLSL reference compiler, then compiles SPIR-V to different flavors of GLSL, different flavors of HLSL, Metal or even AGAL. It currently does not do any optimization passes.
krafix is already pretty solid and is used for http://kha.tech and it looks like it will be used for https://moltengl.com/moltenvk/ - but for now it's still aimed at adventurous developers who are willing to dive into the code to make things work the way they want (there are some built in assumptions I still need to add parameters for, things like pixel center, depth range,...). Whenever that changes, hopefully soon, I'll add a nice readme and website. But please feel free to ask questions.

**Comment by attilaz** [comment]
thanks for the answer. 
This is just what I need, I will give it a try in a hack-week. Thanks

**Comment by C0lumbo** [comment]
Hi, I'm looking for a solution to be able to write shaders once for an engine that supports Vulkan, DirectX9, DirectX11, metal, GLES2 and GLES3. I was planning on writing my shaders in 'vulkanised' GLSL, compiling to SPIR-V with GLSLang then cross-compiling out to other languages with SPIRV-Cross. Problem is that SPIRV-Cross doesn't support HLSL. Your project looks like it's adding the valuable missing piece I'd need. 

A few months have passed since your response to attilaz - is there any way you could comment again on the state of the project, please? Has it had a chance to be battle-tested on shipped applications at all yet? Are there any large gaps in the SPIRV->HLSL converter?

Thanks.

**Comment by RobDangerous** [comment]
krafix is actively used in Kha and Kore, Kha in particular has a small userbase and there are some smaller shipped games. Most advanced thing currently in development AFAIK is https://www.youtube.com/watch?v=j1riyJilvhs
Also I started to move parts of krafix into SPIRV-Cross to achieve more robustness and battle testing, see https://github.com/KhronosGroup/SPIRV-Cross/issues/28 so HLSL is a little bit in flux right now but that should be resolved soon I hope.
I think outside of the cross-compilers inside Unreal and Unity it's the best thing you will find but pretty sure you will run into some issues nontheless. For example currently it expects OpenGL style GLSL, for Vulkan the resulting SPIR-V is transformed.

**Comment by luboslenco** [comment]
From my experience the software Robert is producing is always extremely well thought out, wouldn't be afraid to jump on any of his projects.

**Comment by RobDangerous** [comment]
As the main attraction is nowadays SPIRVCross I don't think we need a fancy readme here.
